### ISSUE TITLE
500 Internal Server Error - BrowseRecommendations Job

### ISSUE THREAD

**Issue by eml5244** [cmu-sei/GHOSTS-SPECTRE#2]
I am trying to set up SPECTRE, following the [documentation page](https://cmu-sei.github.io/GHOSTS/spectre/). Getting the agents and syncing them works for me, but when going to run the BrowseRecommendations job, I get a 500 Internal Server Error. Please see the attached screenshots for the error found in the docker logs after attempting to run the job:

![image](https://github.com/cmu-sei/GHOSTS-SPECTRE/assets/47199371/6ee7d36b-6fe3-41d5-a6d3-cdc939c16796)
![image](https://github.com/cmu-sei/GHOSTS-SPECTRE/assets/47199371/986e00d4-c6a6-43ff-ad62-2ac4d0a40399)

**Comment by sei-dupdyke** [comment]
Hi, sorry about this.

If you look in the container, can you see if any part of that directory exists? Here would be the process:

docker exec -it ghosts-spectre /bin/bash (or sh)
cd /tmp/ghosts/db
ls

**Comment by sei-dupdyke** [comment]
I looked at the issue this morning, and I have some docker volume mapping dependencies on my test machine that others won't have — so the database can't get to the files that spectre creates.

I'll remove this dependency.

**Comment by sei-dupdyke** [comment]
This has been resolved with v0.1.2.

**Comment by sei-dupdyke** [comment]
Did you sync users first?

**Comment by sei-dupdyke** [comment]
docker pull dustinupdyke/ghosts-spectre:0.1.3

**Comment by eml5244** [comment]
Response output:
![image](https://github.com/cmu-sei/GHOSTS-SPECTRE/assets/47199371/5e2601ff-1a26-4878-9753-33bf3d98410c)

Log output: 
![image](https://github.com/cmu-sei/GHOSTS-SPECTRE/assets/47199371/bcc6a073-ed81-42bf-969d-bd261cc566a5)

**Comment by sei-dupdyke** [comment]
Did you have agent activity in your ghosts core database when you synced?

**Comment by eml5244** [comment]
I had 3 agents running and creating activity. I also am still needing to copy in the config, Controllers, and Infrastructure directories into the container to get the agents to be assigned tags/personas. This is other error that comes up for that (sorry, I missed it in the logs)

![image](https://github.com/cmu-sei/GHOSTS-SPECTRE/assets/47199371/5235cb94-4233-46e2-93dc-f91389ebd4b5)

**Comment by sei-dupdyke** [comment]
Hmm. This level of issue is unfortunate, sorry :( 

I can keep trying to fix these issues, but I also have been thinking about moving the functionality of SPECTRE into Animator, so I am a bit torn on a long-term path forward. I think it probably belongs in Animator because that's where agents are created, and we've been working on "Animations" within that API for keeping agent activity fresh and changing throughout an exercise. Those animations could use the personas and preferences throughout the season to change and modify agent behavior. So, maybe this functionality belongs there.

Or, it could be the case that this application lives on just to process ML payloads, and that Animator does not have that functionality out of the box. So, SPECTRE is a bolt-on to Animator, which is a bolt-on to ghosts core.

Another thing to consider long-term is, IIRC the ML.NET library we used for SPECTRE has likely changed quite a bit since the original implementation, when it was fairly new.

**Comment by sei-dupdyke** [comment]
Ok, 0.1.5 is available. Could you please:

1. Stop the SPECTRE container - `docker stop ghosts-spectre && docker rm ghosts-spectre`
2. Delete the preferences database - 
```bash
docker exec -it ghosts-postgres /bin/bash
psql -U ghosts
\c postgres
drop database preferences;
```
3. Now fire up the new spectre container and it should recreate the database.

Thanks

**Comment by eml5244** [comment]
Still no dice. At first it said there wasn't a preferences database, then it said that there was another session and it wouldn't drop it. Did notice that with this version, the last line of the log has slightly changed. I pulled open some more agents (12 total) and let them run in the background to see if that would help get more data; didn't seem to. "Browse history was 0 and sites was 0 over 33 agents. Exiting..." - but I can see the agents browsing so I know they are.

![image](https://github.com/cmu-sei/GHOSTS-SPECTRE/assets/47199371/0bed468e-82c2-4053-b620-343381391db1)

**Comment by sei-dupdyke** [comment]
With no browse history, I am wondering if agents are reporting in correctly in the core database. If you can, try:

```bash
docker exec -it ghosts-postgres /bin/bash
psql -U ghosts
select count(*) from history_timeline;
```
what is the count?

**Comment by eml5244** [comment]
1223141
![image](https://github.com/cmu-sei/GHOSTS-SPECTRE/assets/47199371/49112954-3017-45cf-a3ba-abb446f8bef1)

**Comment by sei-dupdyke** [comment]
Published new container just now - 0.1.6. You'll need to drop the preferences database again, sorry.

**Comment by eml5244** [comment]
Sorry, didn't get a chance to look at the update again until recently. Still getting the same error.

**Comment by sei-dupdyke** [comment]
I can't recreate this, sorry.

**Comment by L015H4CK** [comment]
Hello, I am also struggling to get SPECTRE running. I encountered the same errors as mentioned before and fixed them myself, e.g. by copying the config files manually (also like mentioned in this thread). I set up the docker containers, copied the config files to the spectre container, ran POST Agents/sync and check with GET /Agents.

At the end, when I try to run "BrowseRecommendations", the first time it simply outputs "Sorry, not enough data generated. Browse history was 0 and sites was 0 over 6 agents. Exiting...".
Running it again results in a Error 500: Internal Server Error.

![Bildschirmfoto vom 2023-12-15 13-41-47](https://github.com/cmu-sei/GHOSTS-SPECTRE/assets/9134144/b15bb561-9a93-4303-8f5c-5c4fac7fa6ee)

Running the above mentioned commands on the postgresql server returns a number above 2000 as well.
I am using the newest versions from dockerhub, i.e. GHOSTS 7.0.50 and SPECTRE 0.1.6.
I will be looking further into this but I thought I should let everyone know that the I encountered the error as well.

Best regards,
L015

**Comment by sei-dupdyke** [comment]
Ugh, can't recreate this either. Sorry.

The technology behind this has moved quite a bit (ML.NET is 1.7 in this project and I think it is currently 3.0+), and I have learned quite a bit too, and so perhaps what needs to happen is that this project gets a major rewrite or at the very least a re-write that makes it easier to run and have successful results.

Sorry, I will try to find time to do this soon.

**Comment by L015H4CK** [comment]
Thank you for your swift response! I totally understand. I will look further into it a bit and maybe I can give some answers soon :)
